// This file is part of simple-http-server. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/simple-http-server/master/COPYRIGHT. No part of simple-http-server, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2018 The developers of simple-http-server. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/simple-http-server/master/COPYRIGHT.


use super::*;
use ::libc::pid_t;
use ::libc::pthread_sigmask;
use ::libc::raise;
use ::libc::SIG_BLOCK;
use ::libc::SIGABRT;
use ::libc::SIGALRM;
use ::libc::SIGBUS;
use ::libc::SIGCHLD;
use ::libc::SIGCONT;
use ::libc::sigfillset;
use ::libc::SIGFPE;
use ::libc::SIGHUP;
use ::libc::SIGILL;
use ::libc::SIGINT;
use ::libc::SIGIO;
use ::libc::SIGKILL;
use ::libc::SIGPIPE;
use ::libc::SIGPROF;
use ::libc::SIGPWR;
use ::libc::SIGQUIT;
use ::libc::SIGSEGV;
use ::libc::SIGSTKFLT;
use ::libc::SIGSYS;
use ::libc::SIGTERM;
use ::libc::SIGTRAP;
use ::libc::SIGTSTP;
use ::libc::SIGTTIN;
use ::libc::SIGTTOU;
use ::libc::SIGURG;
use ::libc::SIGUSR1;
use ::libc::SIGUSR2;
use ::libc::SIGVTALRM;
use ::libc::SIGWINCH;
use ::libc::SIGXCPU;
use ::libc::SIGXFSZ;
use ::libc::uid_t;
use ::std::process::abort;
use ::std::process::exit;


include!("AllSignalReactor.rs");
include!("ArithmeticErrorCode.rs");
include!("BusCode.rs");
include!("BusFaultData.rs");
include!("ChildCode.rs");
include!("ChildData.rs");
include!("Code.rs");
include!("EmulatorTrapCode.rs");
include!("FaultData.rs");
include!("GenericSignalData.rs");
include!("IllegalInstructionCode.rs");
include!("PollCode.rs");
include!("PollData.rs");
include!("SegmentationFaultCode.rs");
include!("SI_.rs");
include!("SignalEPollRegistrationError.rs");
include!("SignalFileDescriptor.rs");
include!("SignalHandler.rs");
include!("SignalReadError.rs");
include!("signalfd.rs");
include!("signalfd_siginfo.rs");
include!("SIGRT.rs");
include!("SpecificSignalData.rs");
include!("SystemCallCode.rs");
include!("SystemCallData.rs");
include!("TrapCode.rs");
include!("UserspaceSignalCode.rs");
